### ISSUE TITLE
Question about paired-end reads

### ISSUE THREAD

**Issue by JFourquet** [endrebak/epic#15]
Hi,

I would like to know if EPIC is able to manage paired-end ChIP-seq reads.
Thanks a lot for your answer,

J. Fourquet

**Comment by endrebak** [comment]
Not currently, but it is a feature I am trying to add right now. If you have some paired end data (chip and input, just the first 10k lines), this would greatly speed up the process.🙂 What I am doing (actually, trying to do) atm is creating fake paired end chip data.

**Comment by endrebak** [comment]
Now it does. See #4 👍

**Comment by JFourquet** [comment]
Hi,
With a little delay, thanks a lot for your answers !
J. Fourquet
