### ISSUE TITLE
Default parameters for gap

### ISSUE THREAD

**Issue by Estel-Kitsune** [endrebak/epic#28]
Hi,

In the doc, the default parameter for the "window size" is 200, and the default parameter for "gap" is 3.

However, "gap" is supposed to be a multiple of "window size". Should you change the default gap value for 400, 600..? Or does that mean that by default the gap is 3 \* 200 = 600?

Thanks,
/Estelle

**Comment by endrebak** [comment]
The latter. Perhaps this needs to be made more clear in the docs somewhere.
