### ISSUE TITLE
Latest version of bioepic on anaconda is 0.0.6

### ISSUE THREAD

**Issue by c-guzman** [endrebak/epic#29]
Installed bioepic through bioconda and latest version is 0.0.6.

**Comment by endrebak** [comment]
Thanks.

I have made a PR, but is not updated for some reason. Will ask about being added to the core so I can make PRs myself.

**Comment by c-guzman** [comment]
Has there been any update on this?

**Comment by endrebak** [comment]
I am busy with other stuff unfortunately :)

Can you `pip install bioepic`? That should give you the latest version.

**Comment by endrebak** [comment]
@c-guzman I uploaded the latest bioepic to bioconda. Enjoy.
