### ISSUE TITLE
Effective genome size for Rnor6

### ISSUE THREAD

**Issue by abhisheksinghnl** [endrebak/epic#34]
Hi 
Could you please let me know, how I can numbers for effective genome size files in the for rat and pig?

And also for broad peaks like K9me2 what settings shall I use?

Thank you

**Comment by endrebak** [comment]
Thanks for your interest in epic :)

I have started computing the egs and chromsizes for 

> rn4 rn5 rn6 susScr3 susScr2

Since epic is so fast, you could try several and see which regions look best (without peeking at the p-values of course).

Since the standard settings are good for H3K27me3 they should work well for other broad modifications. I'll update epic tomorrow with the new genomes.

**Comment by abhisheksinghnl** [comment]
Thank you :)

**Comment by abhisheksinghnl** [comment]
Hi,

Please let me know after you have updated the genomes.

Thank you.

Best regards
Abhishek

**Comment by endrebak** [comment]
There was maintenance of our servers yesterday so the script was ended while running. Restarted it now, might not be finished today. If not, I'll upload them on Monday.

**Comment by endrebak** [comment]
`epic` now includes `rn4`, `rn5` and `rn6`. The pig genomes made my effective genome size script fail, which I will get around to fixing. Dunno when I'll succeed though, but I will be sure to reply here.

`pip install bioepic==0.0.10`

**Comment by abhisheksinghnl** [comment]
Thank you :)

Will wait for update on pig genome

**Comment by endrebak** [comment]
`0.1.11` is out and contains `susScr3`. I am done for the week, but I will add `susScr2` eventually.

**Comment by abhisheksinghnl** [comment]
Thank you

**Comment by endrebak** [comment]
`susScr2` is in `0.1.13`. You can now use upper- or lowercase to write the genome in any way you want now.

`pip install bioepic=0.1.13`.
