### ISSUE TITLE
Usage with multiple treatments and controls

### ISSUE THREAD

**Issue by ksiklenka** [endrebak/epic#35]
If I have ChIP experiments on multiple different treatment groups  (lets say dosage A B C D and a control group) how should I input into epic? Do I list the different treatment in a single command and epic treats them separately? Or should I run epic for each treatment vs a control. 

Also that brings me to confusion in wordage for the control flag. Is it reads from an actual ChIP input (i.e no antibody chromatin DNA) or the IP of an untreated control group?

**Comment by endrebak** [comment]
1)

I would run the all files related to each dosage group separately.

so `epic -t A1.bed A2.bed -c A_I1.bed A_I2.bed`, then `epic -t B1.bed B2.bed -c B_I1.bed B_I2.bed`

2)

The first, I was not thinking of control groups when writing that. If you could suggest a wording that sounds better to biologists, please help me :)

**Comment by endrebak** [comment]
By the way, `epic` contains an option to print a gzipped-matrix of bin counts. These can be used to run linear models on your experiment afterwards. See `--store-matrix`.

Closing this, but feel free to ask more related questions here or start a new thread.
