### ISSUE TITLE
Temporary Directory

### ISSUE THREAD

**Issue by c-guzman** [endrebak/epic#39]
I'm running to a problem where my /tmp folder is running out of space during a pipeline run. I was wondering if there was an option to choose where temporary files are stored for epic?

**Comment by endrebak** [comment]
Thanks for reporting this. I had no idea this could happen. I do not use the tmp folder myself, but I guess unix sort does. Do you have a log of all the output messages when you got the error? This would help me understand where it happened.

**Comment by c-guzman** [comment]
I think this is less of a specific EPIC problem, and more of a general case problem where there are too many programs that store temporary files in the /tmp directory (macs2, epic, deeptools, etc) that don't allow for a change in directory for storing temp files. With enough processes running at one time, the /tmp file gets filled over.

**Comment by endrebak** [comment]
The only thing that uses a tmpdir in my software is the unix sort command. If you want to change the tmpdir when running epic you can do `TMPDIR="your/temp/folder" && epic -h`. Modern versions of sort should respond to the `$TMPDIR` variable.
