### ISSUE TITLE
Paired-end read support

### ISSUE THREAD

**Issue by mictadlo** [endrebak/epic#4]
Hi,
HiChip paper ( http://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-15-280 ) describes how they added paired-end support to Sicer:

_For paired-end reads, the HiChIP pipeline keeps the first end and extends by the fragment length estimated from mapping positions of the two ends, rather than by the average fragment length of the library. Given the variability of fragment lengths across a complex genome like human genome, the use of actual coordinates of mapped pairs is expected to achieve better resolution in signal visualization. The bed file is then used to generate a bedGraph file by the genomeCoverageBed command from BEDTools._

Best wishes,

Michal

**Comment by endrebak** [comment]
Thanks. It is definitely on my todo-list (I just had to find PE libs online, since we have no ChIP-seq PE libs ourselves). I will start experimenting with it soon.

**Comment by endrebak** [comment]
epic now fully supports paired end data, but you need to convert bam them to bedpe first.

```
bedtools bamtobed -pe -i name_sorted_paired_end.bam > file.bedpe
```
