### ISSUE TITLE
Google Groups

### ISSUE THREAD

**Issue by c-guzman** [endrebak/epic#40]
Would it be possible to create a google groups for questions?

I'd like to integrate automatic effective genome size estimation into my chip-seq pipeline, but am having a bit of difficulty and can't find an appropriate place to post this (besides maybe biostars, but it's more of a programming question than a bioinformatic question).

**Comment by endrebak** [comment]
Great idea! I have one here, it just isn't advertised well: https://groups.google.com/forum/m/#!forum/epic-chip-seq

Ps. my iMac is being repaired so answers might be a bit tardy.

**Comment by endrebak** [comment]
Also, I can do the egs computation for you. Which genomes do you need?
