### ISSUE TITLE
-k FLAG

### ISSUE THREAD

**Issue by c-guzman** [endrebak/epic#48]
Can you add more information on the keep duplicate flag? I get an error saying it requires an argument, but i'm not sure what the correct argument would be.

**Comment by endrebak** [comment]
I will do later today. Thanks. This is a bug, because it takes no arguments. It only tells epic that if you have several reads with the same chromosome, start and end (within a single file) they should not be removed.

**Comment by endrebak** [comment]
Thanks for taking the time to report this. As of 0.1.24 it should be a proper flag :) Ps. the default `FDR` cutoff is now 0.05.
