### ISSUE TITLE
Andaconda Update

### ISSUE THREAD

**Issue by c-guzman** [endrebak/epic#49]
EPIC on Anaconda is still at 1.6. I'd like to include and cite it as part of a docker container, unfortunately I require the latest updated version of EPIC which has access to the "-cs" and "-sbw" options.

Thank you! (And sorry for posting so much here)

**Comment by endrebak** [comment]
Uploading to anaconda is such a bother that I very seldom do it,
unfortunately. I'll try to do it tomorrow.

Endre

**Comment by endrebak** [comment]
I have made a PR: https://github.com/bioconda/bioconda-recipes/pull/3459

The tests timed out. I will ask if someone has the time to maintain epic in bioconda, because I don't, unfortunately. (I was not the one who added it to begin with.)

**Comment by endrebak** [comment]
Updated the README with "help wanted" info.

**Comment by endrebak** [comment]
By the way, do not apologize for posting here. I appreciate all the feedback :)

**Comment by endrebak** [comment]
I'll try again sometime this week. Sometimes the tests just time out supposedly, and then you should try again :)

**Comment by endrebak** [comment]
The PR was merged :) `0.1.24` Should be out on bioconda.
