### ISSUE TITLE
Create bigwig files for UCSC genome browser display?

### ISSUE THREAD

**Issue by endrebak** [endrebak/epic#5]
I'd like to create files for displaying in the genome browser. 

Need to find out:

1) Should I create one track with pooled data from all the ChIP files or one bigwig file per ChIP file?

I have never used the GB for displaying data so pinging you @daler. Do you have an opinion/other related suggestions?

**Comment by daler** [comment]
In practice I create my own bigwig files, one per replicate, for QC. But that's outside of any peak/domain caller.

What I've found to be most useful is the signal tracks created by macs2, spp, and sicer that essentially show how the algorithm sees the data.  This is helpful when a collaborator says "why isn't my favorite locus called as a domain" and I have some way of explaining to them or troubleshooting why it wasn't called. So in the case of epic, if the domain calls are from pooled data then a track of pooled data would be useful.
