### ISSUE TITLE
bedtools needs genome

### ISSUE THREAD

**Issue by daler** [endrebak/epic#6]
`bedtools bamtobed` needs a genome file on recent (within the last few years?) versions of bedtools. Using BAM files as input is not possible with the bedtools versions available in bioconda due to this [call to bedtools](https://github.com/endrebak/epic/blob/master/epic/windows/count/count_reads_in_windows.py#L62).

**Comment by endrebak** [comment]
Nice catch, now next on my todo. Thanks to your last PR, this will be super easy to solve with the genome size files from pkg_utils.

**Comment by endrebak** [comment]
The bug was actually that I used bedToBam not bamToBed. This was fixed a while ago, but I must have gotten confused by git. (Wonder what other regressions I introduced?) Thanks again.

**Comment by c-guzman** [comment]
This is still a problem using epic version 0.0.6
